# Github workflow to test Pang

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install LilyPond
      run: |
        lilypond_version=2.24.3
        lilypond_archive=lilypond-${lilypond_version}-linux-x86_64.tar.gz
        lilypond_url=https://gitlab.com/lilypond/lilypond/-/releases/
        lilypond_url=${lilypond_url}/v${lilypond_version}/downloads/${lilypond_archive}
        echo ${lilypond_url}
        cd /tmp
        wget -q ${lilypond_url}
        tar -xf ${lilypond_archive}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip coverage
    - name: Log environment variable(s)
      run: |
        echo $PATH
    - name: Install Abjad
      run: |
        # install without development dependencies
        git clone https://github.com/Abjad/abjad.git /tmp/abjad
        pip install /tmp/abjad
    - name: Install Nauert
      run: |
        git clone https://github.com/Abjad/abjad-ext-nauert.git /tmp/abjad-ext-nauert
        pip install /tmp/abjad-ext-nauert
    - name: Install dependencies
      run: |
        export PATH=/tmp/lilypond-2.24.3/bin:/home/runner/bin:$PATH
        python -m pip install -e .[test]
        black --version
        flake8 --version
        isort --version
        mypy --version
        pip --version
        pytest --version
        lilypond --version
    - name: Checks and Tests
      run: |
        export MYPYPATH=$MYPYPATH:/tmp/abjad
        export MYPYPATH=$MYPYPATH:/tmp/abjad-ext-nauert
        export PATH=/tmp/lilypond-2.24.3/bin:/home/runner/bin:$PATH
        make black-check
        make flake8
        make isort-check
        make mypy
        make pytest
